gacha_attempts = 3
iguanadon_attempts = 3
pego_attempts = 3
grinder_attempts = 3
dedi_handshake_recovery_attempts = 3
time_to_reberry = 0.01  # in hours
render_attempts = 3
linked_poly = False
y_trap = False
